FROM eclipse-temurin:21-jdk

WORKDIR /my-app-l1-v1

# Copy jar file
COPY target/my-app-l1-v1.jar my-app-l1-v1.jar

# Expose Spring Boot port
EXPOSE 8090

# Run the accounts
ENTRYPOINT ["java","-jar","accounts-v1.jar"]